### ISSUE TITLE
user/task/list changes

### ISSUE THREAD

**Issue by henry-512** [Capstone-US-Army-PEOSTRI/peostri-lms#55]
`user/task/list` divided into new routes

`user/tasks/assigned/list` lists tasks assigned to the authuser
`user/tasks/team/list` lists tasks assigned to the authuser's team(s)mates
`user/tasks/all/list` lists all tasks (same as `admin/tasks/list`)

`user/tasks/default/list` uses the authuser's permissions (`taskFetching` or `projectFetching`) to determine which of the above to use

**Comment by henry-512** [comment]
same for projects as `user/projects`

**Comment by henry-512** [comment]
prefix `user/` has been removed, routes should be like `task/assigned/list`

**Comment by Syzco** [comment]
Implemented
