### ISSUE TITLE
module template addition flickering

### ISSUE THREAD

**Issue by henry-512** [Capstone-US-Army-PEOSTRI/peostri-lms#72]
adding a module template causes the module name to flicker

**Comment by Syzco** [comment]
Are you on the V4 update or on the original?

**Comment by henry-512** [comment]
whatever version's on the website, ben discovered it

**Comment by Syzco** [comment]
@henry-512 This is caused due to the "q" filter not working properly on the backend. 

`GET http://localhost:5000/api/v1/admin/template/modules/list?filter={"q":"Material Release Validation (MRV) Classified"}&range=0&range=24&sort=id&sort=DESC` Yields 0 results.
