### ISSUE TITLE
On /projects/list and projects/:id give expensive calculations

### ISSUE THREAD

**Issue by Syzco** [Capstone-US-Army-PEOSTRI/peostri-lms#81]
I know those aren't the specific routes, but you get the gist.

I would like to have fields for:
Modules In Progress -> Array of Modules In Progress
Tasks in Progress -> Array of Tasks In Progress
Awaiting Users -> Array of Users with Tasks In Progress

Another alternative is to allow:
`projects/:project_id/modules/:module_id` with filters enabled, so I can access the status field. 
`projects/:project_id/tasks/:task_id` with filters enabled, so I can access the status field. 

Awaiting users I don't think will be easily accessible with another route, so that may have to be appended to the original.

**Comment by henry-512** [comment]
modules in progress for a project are already obtainable with `projects/all/list` (or default/assigned) filtering on `project='projects/some-key', status='SOME_STATUS'`

tasks in progress for a project will be obtainable after  I cache the project in a task (similar filtering to modules)

awaiting users will use a new route `users/awaiting/list`

**Comment by henry-512** [comment]
added modules user routes. `modules/all/list` supports queries on `project` and status
