### ISSUE TITLE
Change notification to more legible information

### ISSUE THREAD

**Issue by Syzco** [Capstone-US-Army-PEOSTRI/peostri-lms#82]
`projects/id` is not a user friendly way of describing a project. 

Use `title` or something like that. Notifications are a content field, so what is sent is displayed.

**Comment by henry-512** [comment]
Notifications and user logs have a `sender` field of the form:
```typescript
display: string // display name (ie project/task title)
resource: string // resource name (ie `project`, `module`, `task`, etc)
id: string // key (without resource/ prefix) that generated the notification/log
```
The original sender source can be retrieved with `sender.resource`/`sender.id`
